- id: '1729405380775'
  alias: Turn off Garage Outside Lights at Sunrise
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.garage_garage_door_lights
  mode: single
- id: '1729405495328'
  alias: Turn On Garage Outside Lights at Sunset
  description: ''
  triggers:
  - trigger: sun
    event: sunset
    offset: 0
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.garage_garage_door_lights
  mode: single
- id: '1729645072575'
  alias: Arm Home at 11PM
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - parallel:
    - if:
      - condition: device
        device_id: 80b5e1db60d2b669d597a4853024b0da
        domain: lock
        entity_id: 6cc6df4fa85a131913ec921fc2a7389e
        type: is_unlocked
      then:
      - device_id: 80b5e1db60d2b669d597a4853024b0da
        domain: lock
        entity_id: 6cc6df4fa85a131913ec921fc2a7389e
        type: lock
    - if:
      - condition: device
        device_id: 4f6f930545e325cf48864f58dcc05858
        domain: alarm_control_panel
        entity_id: c8ab202e7332a54560d2922b59251b48
        type: is_disarmed
      then:
      - device_id: 4f6f930545e325cf48864f58dcc05858
        domain: alarm_control_panel
        entity_id: c8ab202e7332a54560d2922b59251b48
        type: arm_home
  mode: single
- id: '1729646385220'
  alias: Disarm Home at Dawn
  description: ''
  triggers:
  - trigger: time
    at: sensor.sun_next_dawn
  conditions: []
  actions:
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    data:
      code: '0223'
    target:
      entity_id: alarm_control_panel.vivint_smart_hub
  mode: single
- id: '1730139479555'
  alias: Disarm when I Arrive Home
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.andrew
    zone: zone.home
    event: enter
  conditions: []
  actions:
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    data:
      code: '0223'
    target:
      entity_id: alarm_control_panel.vivint_smart_hub
  mode: single
- id: '1730160565794'
  alias: Run Away Mode Script when I Leave Home
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.andrew
    zone: zone.home
    event: leave
  conditions: []
  actions:
  - action: script.away_mode
    metadata: {}
    data: {}
  mode: single
- id: '1730211721384'
  alias: Turn on A/C when I leave Work
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.andrew
    zone: zone.work
    event: leave
  conditions: []
  actions:
  - action: climate.set_temperature
    metadata: {}
    data:
      temperature: 74
      hvac_mode: cool
    target:
      entity_id: climate.ecobee_thermostat
  mode: single
- id: '1731123391587'
  alias: Wake Up
  description: ''
  use_blueprint:
    path: steku/parabolic_alarm.yaml
    input:
      alarm_start_time: input_datetime.time
      workday_sensor: binary_sensor.workday_sensor
      alarm_script: script.light_sunrise_2
      target_light: light.left_nightstand_light
