- id: '1732597711409'
  alias: New automation
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - light.kitchen_1_light
  conditions: []
  actions:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.kitchen_2_identify_2
  mode: single
- id: '1732597762586'
  alias: New automation2
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - number.kitchen_4_start_up_current_level
    above: 55
  conditions: []
  actions:
  - action: camera.disable_motion_detection
    metadata: {}
    data: {}
    target:
      entity_id: camera.vivint_pool_camera
  mode: single
