homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  language: en
  country: US
  currency: USD

default_config:

config:

# frontend:
#   themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automation
script: !include scripts.yaml
scene: !include scenes.yaml
