homeassistant:
  name: "Bonanza"

default_config:

#### Dashboard ###################################
frontend:
  themes: !include_dir_merge_named frontend/themes/
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

lovelace: !include_dir_list dashboard
  mode: yaml
  resources:
    - url: /hacsfiles/hass-hue-icons/hass-hue-icons.js
      type: module
    - url: /hacsfiles/lovelace-hue-like-light-card/hue-like-light-card.js
      type: module

#### Media ###################################
# media_dirs: !secret media_dirs

#### To allow creation in the GUI ###################################
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#### YAML controlled ###################################
automation dir: !include_dir_merge_list automation/
script dir: !include_dir_merge_named script/
scene dir: !include_dir_merge_list scene/
template: !include_dir_merge_named template/