homeassistant:

default_config:

#### Dashboard ###################################
frontend:
  themes: !include_dir_merge_named frontend/themes/
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/hass-hue-icons/hass-hue-icons.js
      type: module
    - url: /hacsfiles/lovelace-hue-like-light-card/hue-like-light-card.js
      type: module

#### Media ###################################
# media_dirs: !secret media_dirs

#### GUI ###################################
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#### Directories ###################################
automation dir: !include_dir_merge_list automation/
script dir: !include_dir_merge_named script/
scene dir: !include_dir_merge_list scene/
template: !include_dir_merge_named template/