homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  language: en
  country: US
  currency: USD

config:

config split: !include_dir_named integration