homeassistant:
  # Bootstraps the Home Assistant core configuration
  packages: !include_dir_named integrations

# ---------------- Split config ----------------
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
template: !include_dir_merge_list templates/
input_boolean: !include_dir_merge_named input_booleans/
