views:
  - type: sections
    max_columns: 4
    title: Snapshot
    path: snapshot
    icon: hue:bulb-group-classic-4-alt
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Hue
          - type: custom:hue-like-light-card
            title: All Hue
            icon: hue:bulb-group
            description: false

            entities:
              - light.bar_hue
              - light.kitchen_hue
              - light.living_room_hue
              - light.office_hue
              - light.primary_bedroom_hue

            # Keep your “hue-screen” behavior
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldAction: hue-screen
            onHoldAction: hue-screen

            # Manually define scenes that call your Nilsreiter script
            scenes:
              - entity: scene.all_hue_energize
                title: Energize
                icon: mdi:white-balance-sunny
                color: "#00BFFF"

              - entity: scene.all_hue_savanna_sunset
                title: Savanna sunset
                icon: mdi:weather-sunset
                color: "#FF8C00"
                    
          - type: custom:hue-like-light-card
            title: All Hue
            description: false
            icon: hue:bulb-group
            scenes: []
            entities:
              - light.bar_hue
              - light.kitchen_hue
              - light.living_room_hue
              - light.office_hue
              - light.primary_bedroom_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.all_hue_scenes
            onHoldData: script.all_hue_scenes
          - type: custom:hue-like-light-card
            title: Main Hue
            description: false
            icon: hue:bulb-group
            entities:
              - light.bar_hue
              - light.kitchen_hue
              - light.living_room_hue
              - light.office_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.main_hue_scenes
            onHoldData: script.main_hue_scenes
    cards: []