views:
  - type: sections
    max_columns: 4
    title: Snapshot
    path: snapshot
    icon: hue:home
    sections:
      - type: grid
        cards:
          - type: heading
            heading_style: subtitle
            heading: Home
            badges:
              - type: entity
                entity: climate.ecobee_thermostat
                color: state
                show_state: true
                show_icon: true
                tap_action:
                  action: more-info
                state_content:
                  - hvac_action
                  - temperature
              - type: entity
                entity: alarm_control_panel.vivint_smart_hub
                color: state
                show_state: true
                show_icon: true
                tap_action:
                  action: more-info
              - type: entity
                entity: cover.ratgdov25i_4a1c34_door
                show_state: true
                show_icon: true
                color: state
                tap_action:
                  action: toggle
                state_content:
                  - state
                  - current_position
            icon: ''
          - type: picture-elements
            image: /api/image/serve/4de88f8dfb986a1f54b22ab7011da710/512x512
            elements:
              - type: state-icon
                entity: light.vanity_lights
                icon: mdi:lightbulb
                style:
                  left: 22%
                  top: 86%
                tap_action:
                  action: toggle
              - type: state-icon
                entity: light.primary_bedroom_right_nightstand_light
                icon: hue:bulb-classic
                style:
                  left: 4%
                  top: 37%
                tap_action:
                  action: toggle
              - type: state-icon
                entity: light.primary_bedroom_left_nightstand_light
                icon: hue:bulb-classic
                style:
                  left: 4%
                  top: 55%
                tap_action:
                  action: toggle
              - type: state-icon
                entity: light.office_light_1
                icon: hue:bulb-classic
                style:
                  left: 49%
                  top: 76%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.office_light_2
                icon: hue:bulb-classic
                style:
                  left: 51%
                  top: 75%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.office_light_3
                icon: hue:bulb-classic
                style:
                  left: 50%
                  top: 74%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.kitchen_light_1
                icon: hue:bulb-classic
                style:
                  left: 68%
                  top: 39%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.kitchen_light_2
                icon: hue:bulb-classic
                style:
                  left: 61%
                  top: 46%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.bar_light_1
                icon: hue:bulb-classic
                style:
                  left: 57%
                  top: 37%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.bar_light_2
                icon: hue:bulb-classic
                style:
                  left: 65%
                  top: 31%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.living_room_spotlight
                icon: hue:bulb-classic
                style:
                  left: 60%
                  top: 5%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: light.living_room_light_strip
                icon: hue:lightstrip
                style:
                  left: 69%
                  top: 15%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: switch.garage_door_lights
                icon: mdi:lightbulb
                style:
                  left: 95%
                  top: 98%
                tap_action:
                  action: toggle
              - type: state-icon
                entity: switch.garage_door_lights
                icon: mdi:lightbulb
                style:
                  left: 60%
                  top: 98%
                tap_action:
                  action: toggle
              - type: state-icon
                entity: light.living_room_ceiling_fan_light
                icon: mdi:ceiling-fan-light
                style:
                  left: 60%
                  top: 12%
                tap_action:
                  action: none
                state_color: true
                hold_action:
                  action: none
              - type: state-icon
                entity: fan.living_room_ceiling_fan
                icon: mdi:ceiling-fan
                style:
                  left: 60%
                  top: 12%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-label
                entity: sensor.roaming_smartsensor_temperature
                style:
                  left: 28%
                  top: 25%
                  color: purple
                tap_action:
                  action: nothing
                hold_action:
                  action: nothing
              - type: state-label
                entity: sensor.ecobee_thermostat_current_temperature
                style:
                  left: 75%
                  top: 31%
                  color: purple
                tap_action:
                  action: nothing
                hold_action:
                  action: nothing
              - type: state-label
                entity: sensor.tower_fan_temperature
                style:
                  left: 13%
                  top: 45%
                  color: purple
                tap_action:
                  action: nothing
                hold_action:
                  action: nothing
              - type: state-icon
                entity: binary_sensor.vivint_master_bedroom_sliding_door_sensor
                icon: mdi:door-sliding-open
                style:
                  left: 9%
                  top: 29%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.vivint_dining_room_sliding_door_sensor
                icon: mdi:door-sliding-open
                style:
                  left: 29%
                  top: 33%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.vivint_kitchen_sliding_door_sensor
                icon: mdi:door-sliding-open
                style:
                  left: 38%
                  top: 25%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: lock.vivint_front_door_lock
                style:
                  left: 32%
                  top: 78%
                hold_action:
                  action: none
                tap_action:
                  action: toggle
              - type: state-icon
                entity: cover.ratgdov25i_4a1c34_door
                style:
                  left: 76%
                  top: 87%
                tap_action:
                  action: toggle
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.roaming_smartsensor_occupancy
                state_color: true
                style:
                  left: 51%
                  top: 6%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.vivint_dining_room_motion_sensor
                style:
                  left: 27%
                  top: 71%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - entity: binary_sensor.vivint_doorbell_camera_motion
                type: state-icon
                style:
                  left: 27%
                  top: 78%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.vivint_driveway_camera_motion
                style:
                  left: 90%
                  top: 97%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: binary_sensor.vivint_pool_camera_motion
                style:
                  left: 44%
                  top: 6%
                tap_action:
                  action: none
                hold_action:
                  action: none
              - type: state-icon
                entity: alarm_control_panel.vivint_smart_hub
                style:
                  left: 50%
                  top: 90%
                hold_action:
                  action: none
                tap_action:
                  action: more-info
            grid_options:
              columns: full
              rows: 8
        column_span: 1
      - type: grid
        cards:
          - type: heading
            heading: Cameras
          - type: vertical-stack
            cards:
              - camera_view: live
                type: picture-glance
                title: Doorbell
                entities:
                  - camera.vivint_doorbell_camera
                camera_image: camera.vivint_doorbell_camera
              - camera_view: live
                type: picture-glance
                title: Driveway
                entities:
                  - camera.vivint_driveway_camera
                camera_image: camera.vivint_driveway_camera
              - camera_view: live
                type: picture-glance
                title: Pool
                entities:
                  - camera.vivint_pool_camera
                camera_image: camera.vivint_pool_camera
    cards: []