views:
  - type: sections
    max_columns: 4
    title: Snapshot
    path: snapshot
    icon: hue:bulb-group-classic-4-alt
    sections:
      - type: grid
        cards:
          - type: heading
            heading: Hue
          - type: custom:hue-like-light-card
            title: All Hue
            description: false
            icon: hue:bulb-group
            entity: light.generic_zigbee_coordinator_ezsp_all_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.hue_scene_all_hue
            onHoldData: script.hue_scene_all_hue
          - type: custom:hue-like-light-card
            title: Main Hue
            description: false
            icon: hue:bulb-group
            entity: light.generic_zigbee_coordinator_ezsp_main_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.main_hue_scenes
            onHoldData: script.main_hue_scenes
          - type: custom:hue-like-light-card
            title: Kitchen Hue
            description: false
            icon: hue:bulb-group
            entity: light.generic_zigbee_coordinator_ezsp_kitchen_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.kitchen_hue_scenes
            onHoldData: script.kitchen_hue_scenes
          - type: custom:hue-like-light-card
            title: Living Room Hue
            description: false
            icon: hue:bulb-group
            entity: light.generic_zigbee_coordinator_ezsp_living_room_hue
            offClickAction: hue-screen
            onClickAction: hue-screen
            offHoldData: script.living_room_hue_scenes
            onHoldData: script.living_room_hue_scenes
    cards: []
