homeassistant:
  name: "Bonanza"
  customize: !include_dir_merge_named customize/entities/
  customize_glob: !include customize/customize_glob.yaml

default_config:

# ---------------- Dashboards ----------------
frontend:
  themes: !include_dir_merge_named frontend/themes/
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js

lovelace:
  resource_mode: yaml
  resources:
    - url: /hacsfiles/hass-hue-icons/hass-hue-icons.js
      type: module
    - url: /hacsfiles/lovelace-hue-like-light-card/hue-like-light-card.js
      type: module

  dashboards:
    lovelace:
      mode: yaml
      filename: dashboards/ui-lovelace.yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      require_admin: false

    lovelace-lights:
      mode: yaml
      filename: dashboards/hue-control.yaml
      title: Hue Control
      icon: hue:bulb-group-classic-4-alt
      show_in_sidebar: true
      require_admin: false

# ---------------- Networking ------------------
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.68.20

# ---------------- Split config ----------------
automation: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include_dir_merge_list scenes/
template: !include_dir_merge_list templates/
input_boolean: !include_dir_merge_named input_booleans/
