# -----------------------------------------------------------------------------
# Automation: Open Garage Door in the Morning
# Automatically opens the garage door if the interior garage door is opened 
# between 7:00 AM and 9:00 AM on a workday (per the workday sensor).
# -----------------------------------------------------------------------------

- alias: Garage Door Open in the Morning

  id: "garage_door_open_in_the_morning"  # Unique ID for UI editing/tracking
  mode: single         # Prevents overlapping execution

  # -----------------------------------------------------------------------------
  # Triggers
  # Fires when the interior garage door sensor changes from 'off' (closed) to 'on' (open).
  # -----------------------------------------------------------------------------
  trigger:
    - platform: state
      entity_id: binary_sensor.vivint_interior_garage_door_sensor
      from: "off"
      to: "on"

  # -----------------------------------------------------------------------------
  # Conditions
  # Only continues if the current time is between 7:00 AM and 9:00 AM,
  # AND it is a workday, as determined by the binary_sensor.workday_sensor.
  # -----------------------------------------------------------------------------
  condition:
    - condition: time
      after: "07:00:00"
      before: "09:00:00"

    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"

  # -----------------------------------------------------------------------------
  # Actions
  # Opens the main garage door if conditions and triggers are met.
  # -----------------------------------------------------------------------------
  action:
    - service: cover.open_cover
      target:
        entity_id: cover.garage_door
