- alias: Open Garage Door in the Morning
  id: '1734380160894'
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.vivint_interior_garage_door_sensor
    from: 'off'
    to: 'on'
  conditions:
  - condition: time
    before: 09:00:00
    weekday:
    - mon
    - tue
    - wed
    after: 07:00:00
  actions:
  - action: cover.open_cover
    metadata: {}
    data: {}
    target:
      entity_id: cover.ratgdov25i_4a1c34_door
  mode: single