- alias: Arm Home at 11PM
  id: "1729645072575"
  triggers:
    - trigger: time
      at: "23:00:00"
  actions:
    - parallel:
        - if:
            - condition: device
              device_id: 80b5e1db60d2b669d597a4853024b0da
              domain: lock
              entity_id: lock.vivint_front_door_lock
              type: is_unlocked
          then:
            device_id: 80b5e1db60d2b669d597a4853024b0da
            domain: lock
            entity_id: lock.vivint_front_door_lock
            type: lock
        - if:
            - condition: device
              device_id: 4f6f930545e325cf48864f58dcc05858
              domain: alarm_control_panel
              entity_id: alarm_control_panel.vivint_smart_hub
              type: is_disarmed
          then:
            device_id: 4f6f930545e325cf48864f58dcc05858
            domain: alarm_control_panel
            entity_id: alarm_control_panel.vivint_smart_hub
            type: arm_home
