# -----------------------------------------------------------------------------
# Automation: Bridge Hue-Like Card scenes to Nilsreiter script
# Calls your script with the proper scene name when a proxy scene is tapped.
# -----------------------------------------------------------------------------
- alias: Bridge Hue Card → Nilsreiter
  id: bridge_hue_card_to_nilsreiter
  mode: single

  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: scene
        service: turn_on

  variables:
    eid: >-
      {% set sd = trigger.event.data.service_data %}
      {% if sd is mapping %}
        {% if sd.entity_id is string %}{{ sd.entity_id }}
        {% elif sd.entity_id is iterable %}{{ sd.entity_id[0] }}
        {% else %}{{ '' }}{% endif %}
      {% else %}{{ '' }}{% endif %}

  condition:
    - condition: template
      value_template: >-
        {{ eid in [
          'scene.all_hue_energize',
          'scene.all_hue_savanna_sunset',
          'scene.main_hue_bright',
          'scene.main_hue_concentrate',
          'scene.main_hue_nightlight',
          'scene.main_hue_savanna_sunset'
        ] }}

  action:
    - choose:
        # -------- All Hue → script.all_hue_scenes --------
        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.all_hue_energize' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.all_hue_scenes }
              data:
                variables:
                  scene: "Energize"

        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.all_hue_savanna_sunset' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.all_hue_scenes }
              data:
                variables:
                  scene: "Savanna sunset"

        # -------- Main Hue → script.main_hue_scenes --------
        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.main_hue_bright' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.main_hue_scenes }
              data:
                variables:
                  scene: "Bright"

        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.main_hue_concentrate' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.main_hue_scenes }
              data:
                variables:
                  scene: "Concentrate"

        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.main_hue_nightlight' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.main_hue_scenes }
              data:
                variables:
                  scene: "Nightlight"

        - conditions:
            - condition: template
              value_template: "{{ eid == 'scene.main_hue_savanna_sunset' }}"
          sequence:
            - service: script.turn_on
              target: { entity_id: script.main_hue_scenes }
              data:
                variables:
                  scene: "Savanna sunset"
