# -----------------------------------------------------------------------------
# Automation: Fan on if living room warm and I'm home
# Turns on the living room ceiling fan at full speed when the thermostat
# temperature goes above 70°F, but only if:
# - You are home, and
# - The fan is currently off
# -----------------------------------------------------------------------------

- alias: Fan on if Living Room Warm and I'm Home

  id: "fan_on_if_living_room_warm_and_im_home"  # Unique identifier managed by Home Assistant
  mode: single         # Prevents multiple overlapping executions

  # -----------------------------------------------------------------------------
  # Triggers
  # Activates when the Ecobee thermostat reports a temperature above 70°F.
  # -----------------------------------------------------------------------------
  trigger:
    - platform: numeric_state
      entity_id: sensor.thermostat_current_temperature
      above: 70

  # -----------------------------------------------------------------------------
  # Conditions
  # A. You must be home (based on person.andrew state).
  # B. The fan must currently be off.
  # -----------------------------------------------------------------------------
  condition:
    - condition: state
      entity_id: person.andrew
      state: "home"

    - condition: state
      entity_id: fan.living_room_ceiling_fan
      state: "off"

  # -----------------------------------------------------------------------------
  # Actions
  # 1. Turn on the ceiling fan.
  # 2. Set the fan speed to 100%.
  # -----------------------------------------------------------------------------
  action:
    - service: fan.turn_on
      target:
        entity_id: fan.living_room_ceiling_fan

    - service: fan.set_percentage
      target:
        entity_id: fan.living_room_ceiling_fan
      data:
        percentage: 100
