- alias: Wake Up
  id: "1731123391587"
  use_blueprint:
    path: steku/parabolic_alarm.yaml
    input:
      alarm_start_time: input_datetime.time
      workday_sensor: binary_sensor.workday_sensor
      alarm_script: script.light_sunrise
      target_light: light.primary_bedroom_left_nightstand_light
