- alias: Wake Up
  id: "1731123391587"
  use_blueprint:
    path: steku/parabolic_alarm.yaml
    input:
      alarm_start_time: input_datetime.time
      workday_sensor: binary_sensor.workday_sensor
      alarm_script: script.light_sunrise
      target_light: light.primary_bedroom_left_nightstand_light

- alias: Turn off Garage Outside Lights at Sunrise
  id: "1729405380775"
  triggers:
    - trigger: sun
      event: sunrise
      offset: 0
  actions:
    - action: switch.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: switch.garage_door_lights

- alias: Turn On Garage Outside Lights at Sunset
  id: "1729405495328"
  triggers:
    - trigger: sun
      event: sunset
      offset: 0
  conditions: []
  actions:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.garage_door_lights

- alias: Turn On Main Light when I Arrive Home and it's Dark
  id: "1732354527388"
  trigger:
    - platform: zone
      entity_id: person.andrew
      zone: zone.home
      event: enter
  condition:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
  action:
    - service: script.turn_on
      target:
        entity_id: script.hue_scene_all_hue
      data:
        variables:
          scene: Unwind
  mode: single
