- alias: Run Away Mode Script when I Leave Home
  id: "1730160565794"
  triggers:
    - trigger: zone
      entity_id: person.andrew
      zone: zone.home
      event: leave
  actions:
    - action: script.away_mode

- alias: Arm Home at 11PM
  id: "1729645072575"
  triggers:
    - trigger: time
      at: "23:00:00"
  actions:
    - parallel:
        - if:
            - condition: device
              device_id: 80b5e1db60d2b669d597a4853024b0da
              domain: lock
              entity_id: lock.vivint_front_door_lock
              type: is_unlocked
          then:
            device_id: 80b5e1db60d2b669d597a4853024b0da
            domain: lock
            entity_id: lock.vivint_front_door_lock
            type: lock
        - if:
            - condition: device
              device_id: 4f6f930545e325cf48864f58dcc05858
              domain: alarm_control_panel
              entity_id: alarm_control_panel.vivint_smart_hub
              type: is_disarmed
          then:
            device_id: 4f6f930545e325cf48864f58dcc05858
            domain: alarm_control_panel
            entity_id: alarm_control_panel.vivint_smart_hub
            type: arm_home

- alias: Disarm Home at Dawn
  id: "1729646385220"
  triggers:
    - trigger: time
      at: sensor.sun_next_dawn
  actions:
    - action: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      target:
        entity_id: alarm_control_panel.vivint_smart_hub

- alias: Disarm when I Arrive Home
  id: "1730139479555"
  triggers:
    - trigger: zone
      entity_id: person.andrew
      zone: zone.home
      event: enter
  actions:
    - action: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_code
      target:
        entity_id: alarm_control_panel.vivint_smart_hub
    - action: cover.open_cover
      target:
        entity_id: cover.ratgdov25i_4a1c34_door
